name: Build

on:
  push:

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Build
    runs-on:
      group: builder
      labels: [self-hosted, x64, builder]
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Cache
        uses: actions/cache@v5
        env:
          cache-version: build-v1
        with:
          key: ${{ env.cache-version }}-${{ hashFiles('spago.yaml', 'package.json') }}
          restore-keys: |
            ${{ env.cache-version }}-
          path: |
            ./.spago
            ./output

      - name: Build dev environment
        run: |
          set -e
          ./scripts/build
